require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cut_elaborateds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CutElaborated. As you add validations to CutElaborated, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CutElaborated.create! valid_attributes
      get cut_elaborateds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cut_elaborated = CutElaborated.create! valid_attributes
      get cut_elaborated_url(cut_elaborated)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cut_elaborated_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cut_elaborated = CutElaborated.create! valid_attributes
      get edit_cut_elaborated_url(cut_elaborated)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CutElaborated" do
        expect {
          post cut_elaborateds_url, params: { cut_elaborated: valid_attributes }
        }.to change(CutElaborated, :count).by(1)
      end

      it "redirects to the created cut_elaborated" do
        post cut_elaborateds_url, params: { cut_elaborated: valid_attributes }
        expect(response).to redirect_to(cut_elaborated_url(CutElaborated.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CutElaborated" do
        expect {
          post cut_elaborateds_url, params: { cut_elaborated: invalid_attributes }
        }.to change(CutElaborated, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cut_elaborateds_url, params: { cut_elaborated: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cut_elaborated" do
        cut_elaborated = CutElaborated.create! valid_attributes
        patch cut_elaborated_url(cut_elaborated), params: { cut_elaborated: new_attributes }
        cut_elaborated.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cut_elaborated" do
        cut_elaborated = CutElaborated.create! valid_attributes
        patch cut_elaborated_url(cut_elaborated), params: { cut_elaborated: new_attributes }
        cut_elaborated.reload
        expect(response).to redirect_to(cut_elaborated_url(cut_elaborated))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cut_elaborated = CutElaborated.create! valid_attributes
        patch cut_elaborated_url(cut_elaborated), params: { cut_elaborated: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cut_elaborated" do
      cut_elaborated = CutElaborated.create! valid_attributes
      expect {
        delete cut_elaborated_url(cut_elaborated)
      }.to change(CutElaborated, :count).by(-1)
    end

    it "redirects to the cut_elaborateds list" do
      cut_elaborated = CutElaborated.create! valid_attributes
      delete cut_elaborated_url(cut_elaborated)
      expect(response).to redirect_to(cut_elaborateds_url)
    end
  end
end
