require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elaborated_product_names", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ElaboratedProductName. As you add validations to ElaboratedProductName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ElaboratedProductName.create! valid_attributes
      get elaborated_product_names_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elaborated_product_name = ElaboratedProductName.create! valid_attributes
      get elaborated_product_name_url(elaborated_product_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elaborated_product_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      elaborated_product_name = ElaboratedProductName.create! valid_attributes
      get edit_elaborated_product_name_url(elaborated_product_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ElaboratedProductName" do
        expect {
          post elaborated_product_names_url, params: { elaborated_product_name: valid_attributes }
        }.to change(ElaboratedProductName, :count).by(1)
      end

      it "redirects to the created elaborated_product_name" do
        post elaborated_product_names_url, params: { elaborated_product_name: valid_attributes }
        expect(response).to redirect_to(elaborated_product_name_url(ElaboratedProductName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ElaboratedProductName" do
        expect {
          post elaborated_product_names_url, params: { elaborated_product_name: invalid_attributes }
        }.to change(ElaboratedProductName, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post elaborated_product_names_url, params: { elaborated_product_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elaborated_product_name" do
        elaborated_product_name = ElaboratedProductName.create! valid_attributes
        patch elaborated_product_name_url(elaborated_product_name), params: { elaborated_product_name: new_attributes }
        elaborated_product_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elaborated_product_name" do
        elaborated_product_name = ElaboratedProductName.create! valid_attributes
        patch elaborated_product_name_url(elaborated_product_name), params: { elaborated_product_name: new_attributes }
        elaborated_product_name.reload
        expect(response).to redirect_to(elaborated_product_name_url(elaborated_product_name))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        elaborated_product_name = ElaboratedProductName.create! valid_attributes
        patch elaborated_product_name_url(elaborated_product_name), params: { elaborated_product_name: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elaborated_product_name" do
      elaborated_product_name = ElaboratedProductName.create! valid_attributes
      expect {
        delete elaborated_product_name_url(elaborated_product_name)
      }.to change(ElaboratedProductName, :count).by(-1)
    end

    it "redirects to the elaborated_product_names list" do
      elaborated_product_name = ElaboratedProductName.create! valid_attributes
      delete elaborated_product_name_url(elaborated_product_name)
      expect(response).to redirect_to(elaborated_product_names_url)
    end
  end
end
