require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mature_cuts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MatureCut. As you add validations to MatureCut, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MatureCut.create! valid_attributes
      get mature_cuts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mature_cut = MatureCut.create! valid_attributes
      get mature_cut_url(mature_cut)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mature_cut_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mature_cut = MatureCut.create! valid_attributes
      get edit_mature_cut_url(mature_cut)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MatureCut" do
        expect {
          post mature_cuts_url, params: { mature_cut: valid_attributes }
        }.to change(MatureCut, :count).by(1)
      end

      it "redirects to the created mature_cut" do
        post mature_cuts_url, params: { mature_cut: valid_attributes }
        expect(response).to redirect_to(mature_cut_url(MatureCut.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MatureCut" do
        expect {
          post mature_cuts_url, params: { mature_cut: invalid_attributes }
        }.to change(MatureCut, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mature_cuts_url, params: { mature_cut: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mature_cut" do
        mature_cut = MatureCut.create! valid_attributes
        patch mature_cut_url(mature_cut), params: { mature_cut: new_attributes }
        mature_cut.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mature_cut" do
        mature_cut = MatureCut.create! valid_attributes
        patch mature_cut_url(mature_cut), params: { mature_cut: new_attributes }
        mature_cut.reload
        expect(response).to redirect_to(mature_cut_url(mature_cut))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mature_cut = MatureCut.create! valid_attributes
        patch mature_cut_url(mature_cut), params: { mature_cut: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mature_cut" do
      mature_cut = MatureCut.create! valid_attributes
      expect {
        delete mature_cut_url(mature_cut)
      }.to change(MatureCut, :count).by(-1)
    end

    it "redirects to the mature_cuts list" do
      mature_cut = MatureCut.create! valid_attributes
      delete mature_cut_url(mature_cut)
      expect(response).to redirect_to(mature_cuts_url)
    end
  end
end
