require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quarterings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Quartering. As you add validations to Quartering, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Quartering.create! valid_attributes
      get quarterings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quartering = Quartering.create! valid_attributes
      get quartering_url(quartering)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quartering_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      quartering = Quartering.create! valid_attributes
      get edit_quartering_url(quartering)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Quartering" do
        expect {
          post quarterings_url, params: { quartering: valid_attributes }
        }.to change(Quartering, :count).by(1)
      end

      it "redirects to the created quartering" do
        post quarterings_url, params: { quartering: valid_attributes }
        expect(response).to redirect_to(quartering_url(Quartering.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Quartering" do
        expect {
          post quarterings_url, params: { quartering: invalid_attributes }
        }.to change(Quartering, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post quarterings_url, params: { quartering: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quartering" do
        quartering = Quartering.create! valid_attributes
        patch quartering_url(quartering), params: { quartering: new_attributes }
        quartering.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quartering" do
        quartering = Quartering.create! valid_attributes
        patch quartering_url(quartering), params: { quartering: new_attributes }
        quartering.reload
        expect(response).to redirect_to(quartering_url(quartering))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        quartering = Quartering.create! valid_attributes
        patch quartering_url(quartering), params: { quartering: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quartering" do
      quartering = Quartering.create! valid_attributes
      expect {
        delete quartering_url(quartering)
      }.to change(Quartering, :count).by(-1)
    end

    it "redirects to the quarterings list" do
      quartering = Quartering.create! valid_attributes
      delete quartering_url(quartering)
      expect(response).to redirect_to(quarterings_url)
    end
  end
end
